from bs4 import BeautifulSoup, SoupStrainer
import requests, re, urllib

def app(e):	
	distro = re.search("\w+", p("cat /etc/issue")).group()
	if e == "dnscrypt": 
		l = []
		if re.search("dnscrypt-proxy",p("dnscrypt -V").communicate()[1])

		else:
			try:
				dnscrypt = requests.get("http://download.dnscrypt.org/dnscrypt-proxy/")
				P = BeautifulSoup(dnscrypt.text, parse_only=SoupStrainer('pre'))
				for i in P.select('a'):	
						a = (i.get('href'))
						if "dnscrypt-proxy" in a:
							l.append(a)		
			except Exception: e = "no se pudo establecer coneccion con dnscrypt"
			if len(l) != 0:
				urllib.urlretrieve ("http://download.dnscrypt.org/dnscrypt-proxy/" + l[0], l[0])
				p("bunzip2 -cd dnscrypt-proxy-*.tar.bz2 | tar xvf -")
				p("cd dnscrypt-proxy-*")
				p("./configure && make -j2")
				p("make install")
				dnsserver = open("/etc/resolv.conf", "w")
				dnsserver.write("# Generated by proxjmp\nnameserver 127.0.0.1")
			p("sudo systemctl enable dnscrypt-proxy.service")
		
			

app("dnscrypt")